spring:
  application:
    name: say-hi-gateway
#  profiles:
#    active: dev # dev-本地开发环境, test-测试环境, prod-生产环境
  config:
    import:
      - "classpath:application-common.yaml"
      - "optional:nacos:say-hi-gateway.yaml"

server:
  port: 10086
  tomcat:
    max-swallow-size: -1

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bird
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn