server:
  port: 10086

spring:
  datasource:
    url: jdbc:mysql://192.168.68.198:3306/say_hi?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 192.168.68.198
      port: 6378