@startuml
participant Participant as Foo
actor Actor as Foo1
boundary Boundary as Foo2
control Control as Foo3
entity Entity as Foo4
database Database as Foo5
collections Collections as Foo6
queue Queue as Foo7
participant Bob
participant Alice

autonumber
==标题1==
Foo -> Foo1 : To actor
note left: hahahah
Foo -> Foo2 : To boundary
alt 条件
    Foo -> Foo3 : To control
    Foo -> Foo4 : To entity
    Foo -> Foo5 : To database
else 否则
    Foo -> Foo6 : To collections
end
Foo -> Foo7: To queue
Bob -[#red]>> Alice : hello

autonumber
==标题2==
Bob -> Alice : hello
@enduml