server:
  port: 10001
spring:
  application:
    name: mini-bird-start
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6377
    password:
grpc:
  server:
    in-process-name: say-hi-sdk-grpc
    # 修改服务端默认入参最大大小，默认值为4M ，这里修改为20M   20*1024*1024
    max-inbound-message-size: 20971520
    # grpc 端口号
    port: 11001