spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.68.198:8848
      config:
        server-addr: 192.168.68.198:8848
  datasource:
    url: jdbc:mysql://192.168.68.198:3306/say_hi?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 192.168.68.198
      port: 6378
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

logging:
  level:
    root: info

grpc:
  client:
    say-hi-im-message:
      address: 'discovery:///say-hi-im-message' # 使用发现协议指向服务名
      negotiation-type: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段名(deleted为实体类属性名称)
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0